config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tags
  resources :user_transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :current_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags =Tag.all
  end

  def new
     @tag = Tag.new
  end

  def show
  end

  def create
    @tag= Tag.new(tag_params)
   
    if @tag.save
      redirect_to @tag, notice: "New tag created successfully."
      else
        render :new
    end
  end 

  def update
    if @tag.update(tag_params)
      redirect_to tag_path(@tag)
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end

  private
    def tag_params
      params.require(:tag).permit(:name, :code)
    end 

  def current_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/user_transactions_controller.rb
class UserTransactionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]

  def index
      @users =User.all
    end
    
  

  def show
  end

  def new
    @user= User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
   
    if @user.save
      redirect_to @user, notice: "New user created successfully."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :balance)
    end 

    def current_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_transactions_helper.rb
module UserTransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Financeapplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/_form.html.erb
<%= simple_form_for @tag do |p| %>
  <p>
 <b><%= p.label :'Code:',:class => 'spacinga'%></b>
  <%= p.text_field :code ,required:true ,placeholder:"ENTER CODE OF THE TAG ",:class => 'form-control'%></b>
</p>
<p>
 <b>  <%= p.label :'Name :',:class => 'spacinga'%></b>
  <%= p.text_field :name, as: :text, placeholder: "ENTER NAME OF THE TAG",:class => 'form-control'%></b>
  </p>
 
<div class ="spacinga">
  <%= p.button :submit, :class=> "btn btn-sm btn-primary " %>
   

<% end %>

app/views/tags/edit.html.erb
<<div class="spacing">
  <link rel="stylesheet" href="application.css">
  <h3 style="color:Tomato;">Edit Tag Details</h3></div>
  <%= render "form" %>
</div>

app/views/tags/index.html.erb
<h1>Online Order Form </h1>
<p class="float-right">
  <%= link_to "Add Tag", new_tag_path, class: "btn btn-md btn-primary" %>
</p>

<% unless @tags.blank? %>
  <table class="table table-hover table-bordered table-striped ">
    <thead>
      <tr>
        <th>Sl No.</th>
        <th>Name</th>
        <th>code</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tags.each_with_index do |tag, index| %>
        <tr>
          <td><%= index + 1 %></td>  
          <td><%= tag.name %></td>
          <td><%= tag.code %></td>
          <td>
            <div>
              <%= link_to "Show", tag_path(tag), 
                class: "btn btn-sm btn-success" %>
              <%= link_to "Edit", edit_tag_path(tag), 
                class: "btn btn-sm btn-primary" %>
              <%= link_to "Remove",tag_path(tag), method: 'delete',
                class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %> 
    </tbody>
  </table>
<% else %>
  <center><h3>No tags found to be shown here!</h3></center>
<% end %>

app/views/tags/new.html.erb
<div class="spacing">
  <link rel="stylesheet" href="application.scss">

  <h1 style="color:Tomato;">Create Tag</h1>
  <%= render "form" %>

</div>

app/views/tags/show.html.erb
<center><h3> Tag Details </h3> </center>
<hr>

<div class="col-md-8">
  <table class="table table-striped">
  <tr>
    <th>Tag code</th>
    <td><%= @tag.code %></td>
  </tr> 
  <tr>
    <th>Name</th>
    <td><%= @tag.name %></td>
  </tr>
  </table> 
</div>

<%= link_to 'Back', tags_path,class: "ml-2 btn btn-sm btn-primary" %></div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |p| %>
  <p>
 <b><%= p.label :'NAME:',:class => 'spacinga'%></b>
  <%= p.text_field :name ,required:true ,placeholder:"ENTER NAME OF THE USER ",:class => 'form-control'%></b>
</p>
<p>
 <b>  <%= p.label :'Email :',:class => 'spacinga'%></b>
  <%= p.text_field :Email, as: :text, placeholder: "ENTER EMAILID",:class => 'form-control'%></b>
  </p>
  <p>
 <b><%= p.label :'BANLANCE:',:class => 'spacinga'%></b>
  <%= p.text_field :balance ,required:true ,placeholder:"ENTER EMAILID ",:class => 'form-control'%></b>
</p>
<div class ="spacinga">
  <%= p.button :submit, :class=> "btn btn-sm btn-primary " %>
   

<% end %>

app/views/users/edit.html.erb
<<<div class="spacing">
  <link rel="stylesheet" href="application.css">
  <h3 style="color:Tomato;">Edit user Details</h3></div>
  <%= render "form" %>
</div>

app/views/users/index.html.erb
<h1>Add new user </h1>
<p class="float-right">
  <%= link_to "Add user", new_user_path, class: "btn btn-md btn-primary" %>
</p>
  <table class="table table-hover table-bordered table-striped ">
    <thead>
      <tr>
        <th>Sl No.</th>
        <th>Name</th>
        <th>email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user, index| %>
        <tr>
          <td><%= index + 1 %></td>  
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <div>
              <%= link_to "Show", user_path(user), 
                class: "btn btn-sm btn-success" %>
              <%= link_to "Edit", edit_user_path(user), 
                class: "btn btn-sm btn-primary" %>
              <%= link_to "Remove",user_path(user), method: 'delete',
                class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %> 
    </tbody>
  </table>
<% else %>
  <center><h3>No tags found to be shown here!</h3></center>

app/views/users/new.html.erb
<div class="spacing">
  <link rel="stylesheet" href="application.scss">

  <h1 style="color:Tomato;">Create user</h1>
  <%= render "form" %>

</div>

app/views/users/show.html.erb
<center><h3> User Details </h3> </center>
<hr>

<div class="col-md-8">
  <table class="table table-striped">
  <tr>
    <th>user name</th>
    <td><%= @user.name %></td>
  </tr> 
  <tr>
    <th>Emailid</th>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <th>Balance</th>
    <td><%= @user.balance %></td>
  </tr>
  </table> 
</div>

<%= link_to 'Back', tags_path,class: "ml-2 btn btn-sm btn-primary" %></div>